"""Regenerate the interface index in AGENTS.md.

The index lists every module in the analysis packages together with its public
functions and their one-line summaries, so that a reader can tell what already
exists without reading the source. Modules are parsed with ast and are never
imported, so this is safe to run without the scientific dependencies installed.

Usage from the repository root:

    python3 GenerateInterfaceIndex.py            # print the index
    python3 GenerateInterfaceIndex.py --write    # rewrite AGENTS.md in place
"""
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
PACKAGES = ["Dependencies", "Read", "Plotting"]
AGENTS_FILE = REPO_ROOT / "AGENTS.md"
BEGIN_MARKER = "<!-- BEGIN INTERFACE INDEX (generated by GenerateInterfaceIndex.py) -->"
END_MARKER = "<!-- END INTERFACE INDEX -->"


def summarise(node):
    """Return the first non-empty line of a docstring, or an empty string."""
    doc = ast.get_docstring(node)
    if not doc:
        return ""
    for line in doc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def public_functions(tree):
    """Yield (name, summary) for each public top-level function."""
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                yield node.name, summarise(node)


def build_index():
    lines = [BEGIN_MARKER, ""]
    for package in PACKAGES:
        package_dir = REPO_ROOT / package
        if not package_dir.is_dir():
            continue
        modules = sorted(p for p in package_dir.glob("*.py") if p.name != "__init__.py")
        if not modules:
            continue
        lines.append("### " + package)
        lines.append("")
        for module_path in modules:
            try:
                tree = ast.parse(module_path.read_text(encoding="utf-8"))
            except SyntaxError as error:
                lines.append("- `{}` -- SKIPPED, does not parse: {}".format(
                    module_path.name, error.msg))
                continue
            module_summary = summarise(tree)
            functions = list(public_functions(tree))

            entry = "- `{}.{}`".format(package, module_path.stem)
            if module_summary:
                entry += " -- " + module_summary
            lines.append(entry)
            for name, summary in functions:
                call = "  - `{}(...)`".format(name)
                if summary:
                    call += " -- " + summary
                lines.append(call)
            if not functions and not module_summary:
                lines.append("  - script, no public functions and no module docstring")
        lines.append("")
    lines.append(END_MARKER)
    return chr(10).join(lines)


def main():
    index = build_index()
    if "--write" not in sys.argv:
        print(index)
        return 0

    text = AGENTS_FILE.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        sys.exit(
            "ERROR !!! {} does not contain the index markers. Add these two lines "
            "where the index belongs and rerun:{}{}{}{}".format(
                AGENTS_FILE, chr(10), BEGIN_MARKER, chr(10), END_MARKER))

    start = text.index(BEGIN_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER)
    updated = text[:start] + index + text[end:]

    if updated == text:
        print("Interface index already up to date.")
        return 0

    AGENTS_FILE.write_text(updated, encoding="utf-8")
    print("Rewrote the interface index in {}".format(AGENTS_FILE))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
